package customeroperationsingleton;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Customer extends javax.swing.JFrame {
    Connection connection;
    /**
     * Creates new form Customer
     */
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Customer() {
        initComponents();
        try {
            DBConnection dbconnection=DBConnection.getDBConnection();
            connection=dbconnection.getConnection();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLoad();
    }
    public void tableLoad(){
        try {
            String SQL="SELECT id,name,tel,email,country FROM customer";
            pst=connection.prepareStatement(SQL);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxtBox = new javax.swing.JTextField();
        nameTxtBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTxtBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        replaceComBut = new javax.swing.JButton();
        addComBut = new javax.swing.JButton();
        deleteComBut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        countryTxtBox = new javax.swing.JTextField();
        searchComBut = new javax.swing.JButton();
        clearComBut = new javax.swing.JButton();
        exitComBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setText("Customer Form");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("ID");

        idTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("E-mail");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Tel");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Tel", "E-mail", "Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        replaceComBut.setText("Replace");
        replaceComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceComButActionPerformed(evt);
            }
        });

        addComBut.setText("Add");
        addComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComButActionPerformed(evt);
            }
        });

        deleteComBut.setText("Delete");
        deleteComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteComButActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Country");

        searchComBut.setText("Search");
        searchComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComButActionPerformed(evt);
            }
        });

        clearComBut.setText("Clear All");
        clearComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearComButActionPerformed(evt);
            }
        });

        exitComBut.setText("Exit");
        exitComBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitComButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(countryTxtBox)
                                    .addComponent(telTxtBox)
                                    .addComponent(nameTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(emailTxtBox))
                                .addGap(18, 18, 18)
                                .addComponent(searchComBut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addComBut)
                                .addGap(32, 32, 32)
                                .addComponent(replaceComBut)
                                .addGap(31, 31, 31)
                                .addComponent(deleteComBut)
                                .addGap(18, 18, 18)
                                .addComponent(clearComBut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitComBut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchComBut))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteComBut)
                    .addComponent(replaceComBut)
                    .addComponent(addComBut)
                    .addComponent(clearComBut)
                    .addComponent(exitComBut))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtBoxActionPerformed

    private void addComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComButActionPerformed
        try {
            String id=idTxtBox.getText();
            String name=nameTxtBox.getText();
            int tel=Integer.parseInt(telTxtBox.getText());
            String email=emailTxtBox.getText();
            String country=countryTxtBox.getText();
            
            String SQL="Insert into customer(id, name, tel, email, country) values('"+id+"','"+name+"','"+tel+"','"+email+"','"+country+"')";
//            Statement statement = connection.createStatement();
//            int res = statement.executeUpdate(SQL);
            boolean res = connection.prepareStatement(SQL).execute();
            if(!res){
                JOptionPane.showMessageDialog(this,"Added Success"); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLoad();
        
    }//GEN-LAST:event_addComButActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r=jTable1.getSelectedRow();
        
        String id=jTable1.getValueAt(r, 0).toString();
        String name=jTable1.getValueAt(r,1).toString();
        String tel=jTable1.getValueAt(r, 2).toString();
        String email=jTable1.getValueAt(r, 3).toString();
        String country=jTable1.getValueAt(r, 4).toString();
        
        idTxtBox.setText(id);
        nameTxtBox.setText(name);
        telTxtBox.setText(tel);
        emailTxtBox.setText(email);
        countryTxtBox.setText(country);
        
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void replaceComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceComButActionPerformed
        int x=JOptionPane.showConfirmDialog(this, "Do you want to replace?");
        if(x==0){
            try {
                String id=idTxtBox.getText();
                String name=nameTxtBox.getText();
                int tel=Integer.parseInt(telTxtBox.getText());
                String email=emailTxtBox.getText();
                String country=countryTxtBox.getText();
                
                String SQL="UPDATE customer SET name='"+name+"', tel='"+tel+"',email='"+email+"',country='"+country+"' WHERE id='"+id+"'";
                //Statement statement = connection.createStatement();
                //statement.executeUpdate(SQL);
                connection.prepareStatement(SQL).execute();
                
            } catch (SQLException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tableLoad();
    }//GEN-LAST:event_replaceComButActionPerformed

    private void deleteComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteComButActionPerformed
int x=JOptionPane.showConfirmDialog(this, "Do you want to replace?");
        if(x==0){
            try {
                String id=idTxtBox.getText();
                
                String SQL="DELETE from customer WHERE id='"+id+"'";
                //Statement statement = connection.createStatement();
                //statement.executeUpdate(SQL);
                connection.prepareStatement(SQL).execute();
                
            } catch (SQLException ex) {
                Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tableLoad();
    }//GEN-LAST:event_deleteComButActionPerformed

    private void searchComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComButActionPerformed
        String name=nameTxtBox.getText();
        
        String SQL="SELECT id, name,tel,email,country FROM customer where name LIKE '%"+name+"%'";
        try {
            pst=connection.prepareStatement(SQL);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        //tableLoad();
    }//GEN-LAST:event_searchComButActionPerformed

    private void clearComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearComButActionPerformed
        idTxtBox.setText("");
        nameTxtBox.setText("");
        telTxtBox.setText("");
        emailTxtBox.setText("");
        countryTxtBox.setText("");
        
    }//GEN-LAST:event_clearComButActionPerformed

    private void exitComButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitComButActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitComButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComBut;
    private javax.swing.JButton clearComBut;
    private javax.swing.JTextField countryTxtBox;
    private javax.swing.JButton deleteComBut;
    private javax.swing.JTextField emailTxtBox;
    private javax.swing.JButton exitComBut;
    private javax.swing.JTextField idTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTxtBox;
    private javax.swing.JButton replaceComBut;
    private javax.swing.JButton searchComBut;
    private javax.swing.JTextField telTxtBox;
    // End of variables declaration//GEN-END:variables
}
